---
title: "p8105_hw6_sy3352"
author: "Su Yan"
date: "2025-11-23"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(ggplot2)
set.seed(1)
library(p8105.datasets)
data("weather_df")
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1
```{r}
homicides_df = read_csv("data/homicide-data.csv") |> 
  mutate(location = sprintf("%s, %s", city, state),
         solved = case_when(
           disposition == "Closed by arrest" ~ 1, TRUE ~ 0),
         victim_age = as.numeric(victim_age)
         ) |> 
  filter(!location %in% c("Dallas, TX", "Phoenix, AZ", 
                          "Kansas City, MO", "Tulsa, AL"),
         victim_race %in% c("Black", "White"))
```

```{r}
baltimore_df = homicides_df |> 
  filter(location == "Baltimore, MD")

baltimore_fit = baltimore_df |> 
  glm(solved ~ victim_age + victim_race + victim_sex, data = _, 
      family = binomial()) 

baltimore_results = baltimore_fit |> 
  broom::tidy(conf.int = TRUE, exponentiate = TRUE) |> 
  filter(term == "victim_sexMale") |>
  select(term, adjusted_OR = estimate, conf.low, conf.high, p.value) |> 
  knitr::kable(digits = 3)
baltimore_results
```

```{r}
by_city = homicides_df |> 
  group_by(location) |> 
  nest() |> 
  mutate(glm_model = map(data, ~glm(solved ~ victim_age + victim_race + 
                                      victim_sex, data = .x, family = binomial()
  )),
  results = map(glm_model, ~broom::tidy(.x, conf.int = TRUE, 
                                        exponentiate = TRUE))) |> 
  select(location, results) |> 
  unnest(results) |> 
  filter(term == "victim_sexMale") |>
  select(location, adjusted_OR = estimate, conf.low, conf.high, p.value) 
```

```{r}
by_city_plot = by_city |> 
  ggplot(aes(x = reorder(location, adjusted_OR), y = adjusted_OR)) + 
  geom_point(color = "deeppink", size = 2.5) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        plot.title = element_text(hjust = 0.5)) +
  labs(x = "City", y = "Estimated OR of Male vs Female",
       title = "Comparison for Solving Homicides by Victim Sex of Each City")
by_city_plot
```

## Problem 2
```{r}
boot_weather = weather_df |> 
  select(tmax, tmin, prcp) |> 
  modelr::bootstrap(n = 5000) |> 
  mutate(models = map(strap, \(df) lm(tmax ~ tmin + prcp, data = df)),
         results = map(models, broom::tidy),
         glances = map(models, broom::glance)) |> 
  select(-strap, -models) |> 
  unnest(glances, results)

boot_results = boot_weather |> 
  select(.id, r.squared, term, estimate) |> 
  pivot_wider(names_from = term, values_from = estimate) |> 
  mutate(ratio = tmin/prcp)

boot_r_plot = boot_results |> 
  ggplot(aes(x = r.squared)) +
  geom_histogram()
boot_r_plot

boot_ratio_plot = boot_results |> 
  ggplot(aes(x = ratio)) +
  geom_histogram()
boot_ratio_plot

boot_ci = boot_results |> 
  summarize(
    r.squared_lower = quantile(r.squared, 0.025), 
    r.squared_upper = quantile(r.squared, 0.975),
    ratio_lower = quantile(ratio, 0.025), 
    ratio_upper = quantile(ratio, 0.975)) |> 
  knitr::kable(digits = 3)
boot_ci
```

